/** How severe the skill gap is relative to market demand */
export type GapSeverity = 'critical' | 'high' | 'medium' | 'low';

/** A single skill gap analysis */
export interface SkillGap {
  skillId: string;
  skillName: string;
  /** User's current proficiency 0–10 */
  userLevel: number;
  /** % of job postings requiring this skill 0–100 */
  marketDemand: number;
  /** Computed: marketDemand * ((10 - userLevel) / 10) */
  gapScore: number;
  severity: GapSeverity;
  category: string;
}

/** Full career diagnostic result generated by AI */
export interface DiagnosticResult {
  id: string;
  /** Career readiness score 0–100 */
  readinessScore: number;
  /** How exposed the user's role is to AI displacement 0–100 */
  aiRiskScore: number;
  gaps: SkillGap[];
  careerSummary: string;
  targetRole: string;
  generatedAt: string;
}
